# Generated by Django 4.2.6 on 2024-01-31 18:31

import carts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_created_timestamp_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name=carts.models.CartQueryset.total_price),
        ),
    ]
